### PR TITLE
Added fix functionality

### PR DESCRIPTION
**Pull request by smessimer**
I had to update from Puppet 3 to Puppet 4 and this plug-in found hundreds of cases that would cause failures in Puppet 3 when using Future Parser.  The fix function just lower cases all variable names.

### CODE REVIEW

**Comment by fiddyspence** [comment]
Hi - thanks for the PR - it looks like a simple change, but I think it should have tests to prove that it does what you expect.

**Comment by smessimer** [comment]
Gotcha, I'll add some tests when I get a chance and resubmit the pull request.

**Comment by smessimer** [comment]
I added a simple test to prove out the functionality.  There is a description of how to run the test in test/readme.  I hope this is what you were looking for, otherwise let me know and I can make adjustments.

**Comment by fiddyspence** [comment]
Closed - I added the tests as part of #9 - thanks for the contribution!

**Comment by smessimer** [comment]
My pleasure, thanks!

**Pull request closed without merging**
