### PR TITLE
With the release of puppet-lint 2.0.0, support ~>2.0 versions.

### PR DESCRIPTION
**Pull request by rnelson0**

### CODE REVIEW

**Comment by rnelson0** [comment]
@fiddyspence Had to do some cleanup for travis tests to pass as well. If you can publish this to rubygems afterward that would be awesome, to let people leverage the new puppet-lint 2.0.0 release. Thanks!

**Comment by tuxmea** [comment]
+1

**Comment by rnelson0** [comment]
@fiddyspence Bump!

**Comment by cdenneen** [comment]
@fiddyspence 👍

**Comment by fiddyspence** [comment]
Sorry -miles away - merging

**Comment by rnelson0** [comment]
Thanks for the release too!

**Pull request merged**
